version: '2.1'
services:

  mockserver:
    image: docker.saritasa.com/alpine-mockserver:0.6
    hostname: training-mockserver
    container_name: training-mockserver
    mem_limit: 536870912
    expose:
    - 8000
    environment:
    - SWAGGER_FILE_URL=https://apidocs.saritasa-hosting.com/training/develop/training-latest.yaml
    stdin_open: true
    tty: true
    volumes:
    - .:/home/www/app/data/
