<?php

use Illuminate\Database\Migrations\Migration;

/**
 * Class CreateTables. Bulk create tables
 */
class CreateTables extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $queries = $this->parseMultiSqlFile(__DIR__ . '/basement/db_create.sql');
        foreach ($queries as $query) {
            DB::statement($query);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $queries = $this->parseMultiSqlFile(__DIR__ . '/basement/db_drop.sql');
        foreach ($queries as $query) {
            DB::statement($query);
        }
    }

    /**
     * Parse sql file generated by DeZign for Databases for array of queries
     * @param string $fileName
     * @return array Sql queries
     */
    private function parseMultiSqlFile($fileName)
    {
        $content = file_get_contents($fileName);
        // Replaced \n\n\n and explode by \n\n
        $queries = explode("\n\n", str_replace("\n\n\n", "\n\n", str_replace("\r\n", "\n", $content)));
        // Removed queries that starts like comments
        $queries = array_filter($queries, function ($line) {
            return $line[0] !== '#';
        });

        return $queries;
    }
}
